name: Just Publish
on: push
jobs:
  just-build:
    runs-on: ubuntu-latest
    steps:
      - name: Runner Info
        run: |
          echo "🎉 The job was automatically triggered by a ${{ github.event_name }} event."
          echo "🐧 Now running on a ${{ runner.os }} server hosted by GitHub!"
          echo "🔎 Branch is ${{ github.ref }} ${{ github.repository }} repo"
          echo "💡 The ${{ github.repository }} repo has been cloned to the runner."

      - name: Checkout Repo
        uses: actions/checkout@v2

      - name: Setup Ruby
        uses: actions/setup-ruby@v1
        with:
          ruby-version: '3'
          bundler-cache: true   # Runs 'bundle install' and caches installed gems automatically

      - name: Setup Java / Maven
        uses: actions/setup-java@v2
        with:
          java-version: '8'
          distribution: 'adopt'          

      - name: Install Dependencies
        run:  |
          npm install
          gem install jekyll
          mvn clean install

      - name: Build IG
        run:  |
          npm run sushi
          npm run ig_init

      - name: Create Snapshot Jar
        run:  |
          npm run mvn_snapshot
          npm run copy_snapshot

#      - name: Copy To Documents Folder
#      - run: npm run copy_docs_version

#      - name: Commit Changes
#        run: |
#          git config user.name github-actions
#          git config user.email github.actions@github.com
#          git add .
#          git commit -m "Generated docs"
#          git push          
