name: Release Artifacts
on:
  release:
    branches:
      - master
    tags:
      - "*"
    types:
      - created
      
jobs:
  build-project:
    runs-on: ubuntu-latest
    steps:
      - name: Runner Info
        run: |
          echo "The job was automatically triggered by a ${{ github.event_name }} event."
          echo "Now running on a ${{ runner.os }} server hosted by GitHub!"
          echo "Github repository is ${{ github.repository }}"
          echo "Release tag is ${{ github.ref }}"
          echo "Event_name is ${{ github.event_name }}"

      - name: Checkout Repo
        uses: actions/checkout@v2

      - name: Upload Readme.md
        uses: actions/upload-artifact@v2
        with:
          name: readme
          path: readme.md

      - name: Upload Release Asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: ./readme.md
          asset_name: Readme Markdown
          asset_content_type: text/markdown

#      - name: Upload Release Asset (full-ig.zip)
#        uses: actions/upload-artifact@v2
#        with:
#          name: Full IG Site Specification (fullig.zip)
#          path: build/output/full-ig.zip

#      - name: Upload Release Asset (snapshot.jar)
#        uses: actions/upload-artifact@v2
#        with:
#          name: FHIR Deployment Snapshot Jar
#          path: build/output/*.jar

#      - name: Upload Release Asset (Package.tgz)
#        uses: actions/upload-artifact@v2
#        with:
#          name: Package Tar Archive (package.tgz)
#          path: build/output/package.tgz
