name: Release Notes
# Trigger the workflow on milestone cosed events
on:
  milestone:
    types: [closed]
jobs:
  create-release-notes:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master

      - name: Create Release Notes
        uses: docker://decathlon/release-notes-generator-action:2.0.1
        env:
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
          OUTPUT_FOLDER: temp_release_notes
          USE_MILESTONE_TITLE: "true"

      - name: Upload Release Notes to Wiki
        uses: docker://decathlon/wiki-page-creator-action:latest
        env:
          ACTION_MAIL: cox.stuart@gmail.com 
          ACTION_NAME: coxstuart
          OWNER: coxstuart
          GH_PAT: ${{ secrets.GH_PAT }}
          MD_FOLDER: temp_release_notes
          REPO_NAME: alvearie-fhir-ig
          SKIP_MD: README.md          
